apiVersion: v1
kind: Service
metadata:
  name: egg-on-k8s
spec:
  type: NodePort
  ports:
    - port: 7001
      targetPort: 7001
      protocol: TCP
  selector:
    app: egg-on-k8s 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egg-on-k8s
  labels:
    app: egg-on-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egg-on-k8s
  template:
    metadata:
      labels:
        app: egg-on-k8s
    spec:
      containers:
      - name: egg-on-k8s
        image: egg-on-k8s
        ports:
        - containerPort: 7001
